### ISSUE TITLE
Cargo.lock is missing

### ISSUE THREAD

**Issue by colemickens** [chris-ricketts/keyboard-layouts#1]
This prevents me from packaging it for `nixpkgs`. It would be great to have an easily-deployed virtual keyboard software to run on RPi0s. With NixOS especially, some interesting little things can be built.

**Comment by colemickens** [comment]
I'm not sure if it's appropriate for libraries to checkin their `Cargo.lock` files? Maybe the lib/bin should be split apart?

Are you interested in doing this, and/or would you merge a PR for it?

**Comment by chris-ricketts** [comment]
Thanks @colemickens, I've merged #2
